language: ruby
rvm:
  - "2.0.0"
  - "2.1.7"
  - "2.2.3"
env:
  - TMUX_VERSION=master
  - TMUX_VERSION=2.3
  - TMUX_VERSION=2.2
  - TMUX_VERSION=2.1
  - TMUX_VERSION=2.0
  - TMUX_VERSION=1.9
  - TMUX_VERSION=1.8
  - TMUX_VERSION=1.7
  - TMUX_VERSION=1.6
  - TMUX_VERSION=1.5
matrix:
  fail_fast: true
  allow_failures:
    - env: TMUX_VERSION=1.7
before_install:
  - gem install bundler --no-ri --no-rdoc
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev libncurses-dev
  - git clone https://github.com/tmux/tmux.git tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure && make && sudo make install
  - cd ..
  - tmux -V
script: bundle exec rake test
